### PR TITLE
Test edit flow - not for pushing

### PR DESCRIPTION
**Pull request by jonahgraham**
Trying out what Wim suggested https://www.eclipse.org/lists/platform-dev/msg02996.html

### CODE REVIEW

**Comment by jonahgraham** [comment]
@wimjongman I tried out the flow, but it seems to not work as a contributor?

**Comment by wimjongman** [comment]
Thanks, Jonah! That's a serious issue, I will discuss this with the webmasters. 

https://bugs.eclipse.org/bugs/show_bug.cgi?id=572631

**Review by wimjongman — APPROVED** [review]
Test approve

**Comment by wimjongman** [comment]
Jonah, we changed some workflow settings. Can you again edit a page on https://eclipse.github.io/birt-website/ and make anew PR?

**Comment by jonahgraham** [comment]
Sure - give me a moment.

**Pull request closed without merging**
