### PR TITLE
Test edit flow - not for pushing

### PR DESCRIPTION
**Pull request by jonahgraham**
Another try, see #13 and #11 that came before.

### CODE REVIEW

**Review by wimjongman — APPROVED** [review]
Looks safe to me

**Comment by jonahgraham** [comment]
This was the error

```
  /usr/bin/git push origin gh-pages
  remote: Permission to eclipse/birt-website.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/eclipse/birt-website.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```

**Comment by jonahgraham** [comment]
@wimjongman - FWIW I don't really get how this flow is supposed to work. But the thing that keeps failing is pushing to gh-pages branch. But if that were to have succeeded then my PR generated files would have gone live on gh-pages *before* the changes to the sources was merged to master. The commit that it is trying to create says:

```
Create a commit
  /usr/bin/git commit -m deploy: 2ea43c18657c648dc8ea181683d2542c74bd8634
  [gh-pages 834f796] deploy: 2ea43c18657c648dc8ea181683d2542c74bd8634
   51 files changed, 122 insertions(+), 122 deletions(-)
   delete mode 100644 assets/js/30120b78.04fedf7e.js
   create mode 100644 assets/js/30120b78.a277465c.js
   rename assets/js/{4566acc7.0b5dd70f.js => 4566acc7.ef37e9ed.js} (97%)
   rename assets/js/{8b574076.318d86ee.js => 8b574076.74ed60e5.js} (96%)
   rename assets/js/{runtime~main.ef32f692.js => runtime~main.015716a7.js} (95%)
```

The issue is that 2ea43c18657c648dc8ea181683d2542c74bd8634 does not exist in the repo on the main branch, so the generated version of this (probably) should not be on the gh-pages branch.

I suppose it would be ok if the PR generated 2ea43c18657c648dc8ea181683d2542c74bd8634 and then stuck it in gh-pages under a directory so you could preview it that way.

Anyway, that is my 2cents. Let me know how I can help you test the flow more.

**Comment by wimjongman** [comment]
Hey Jonah.

I actually have to review the PR before the workflow action starts. I did this byusing the "environment" keyword in the action. This takes care of the concerns you mentioned. 

In our case, gh-pages will be a sandbox to review the changes before pushing them to the Eclipse website.

However, it seems that PR's from cloned repos never get write access from the default GITHUB_TOKEN [1]. I'm looking into that.

Cheers,

Wim

[1] https://docs.github.com/en/actions/reference/authentication-in-a-workflow#how-the-permissions-are-calculated-for-a-workflow-job

**Comment by jonahgraham** [comment]
> gh-pages will be a sandbox to review the changes before pushing them to the Eclipse website

Ah, that was the missing piece. Thank you for explaining that to me

Anyway, let me know when/if I can help you test this further.. 

Thanks,
Jonah

**Pull request closed without merging**
